# Generated by Django 3.0.8 on 2020-07-27 13:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingInCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('small_description', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='trending')),
                ('visibility', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('file_attached', models.FileField(blank=True, null=True, upload_to='attachments')),
                ('category', models.CharField(choices=[('academics', 'Academics'), ('administration', 'Administration'), ('tnp', 'Training and Placement'), ('events', 'Events'), ('misc', 'Miscelleneous')], default='misc', max_length=15)),
                ('visible_for_student', models.BooleanField(default=True)),
                ('visible_for_hod', models.BooleanField(default=True)),
                ('visible_for_faculty', models.BooleanField(default=True)),
                ('visible_for_management', models.BooleanField(default=True)),
                ('visible_for_others', models.BooleanField(default=True)),
                ('course_branch_year', models.CharField(blank=True, default='AllCourses-AllBranches-AllYears-AllSections', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.FacultyDetail')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkedNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.Notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
