# Generated by Django 2.2.14 on 2020-08-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkednotice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='bookmarkednotice',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='bookmarkednotice',
            name='notice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notices.Notice'),
        ),
        migrations.AlterField(
            model_name='bookmarkednotice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('academics', 'Academics'), ('administration', 'Administration'), ('tnp', 'Training and Placement'), ('events', 'Events'), ('misc', 'Miscelleneous')], default='misc', max_length=15),
        ),
        migrations.AlterField(
            model_name='notice',
            name='course_branch_year',
            field=models.CharField(blank=True, default='AllCourses-AllBranches-AllYears-AllSections', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.FacultyDetail'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file_attached',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='trendingincollege',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='trending'),
        ),
        migrations.AlterField(
            model_name='trendingincollege',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='trendingincollege',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
    ]
