# Generated by Django 2.2.14 on 2020-08-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200130_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='facultydetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='facultydetail',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='facultydetail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='branch',
            field=models.CharField(blank=True, choices=[('AllBranches', 'None'), ('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('EE', 'Electrical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CE', 'Civil Engineering'), ('IC', 'Instrumentation and Control Engineering'), ('ME', 'Mechanical Engineering'), ('MT', 'Manufacturing Technology')], default='AllBranches', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='course',
            field=models.CharField(blank=True, choices=[('BTech', 'BTech'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('MTech', 'MTech'), ('Humanities', 'Humanities'), ('English', 'English'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Maths', 'Maths'), ('Administration', 'Administration'), ('Maintenance', 'Maintenance'), ('OTHER', 'Others')], default='AllCourses', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='section',
            field=models.CharField(blank=True, choices=[('AllSections', 'None'), ('CSE1', 'CSE1'), ('CSE2', 'CSE2'), ('IT1', 'IT1'), ('IT2', 'IT2'), ('ECE1', 'ECE1'), ('ECE2', 'ECE2'), ('EE1', 'EE1'), ('EE2', 'EE2'), ('EEE1', 'EEE1'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('IC1', 'IC1'), ('IC2', 'IC2'), ('MT1', 'MT1'), ('MT2', 'MT2'), ('ME1', 'ME1'), ('ME2', 'ME2'), ('ME3', 'ME3')], default='AllSections', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
