# Generated by Django 3.0.8 on 2020-07-27 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_laptop_mac_address', models.CharField(default=None, max_length=200, validators=[django.core.validators.RegexValidator(message='Enter MAC Address in Given Format.', regex='^([0-9A-F]{2}[:]){5}([0-9A-F]{2})$')])),
                ('new_laptop_mac_address', models.CharField(blank=True, default=None, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Enter MAC Address in Given Format.', regex='^([0-9A-F]{2}[:]){5}([0-9A-F]{2})$')])),
                ('mac_registered', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
