# Generated by Django 2.2.14 on 2020-08-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_changes_max_length_of_notification_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasetoken',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_preferences',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
